# Uncomment the next line to define a global platform for your project
 platform :ios, '10.0'

target 'LBTAToolsStacking' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for LBTAToolsStacking
  pod 'LBTATools'
  pod 'Texture'
end
